export * from './DashboardPage';
export * from './HomePage';
export * from './LoginPage';
export * from './RegisterPage';
export * from './InfoPage';
export { default as HomePage } from './HomePage';
export * from './AjustesPage';
export * from './ImgPage';
export * from './ContactoPage';
export * from './SubirImgPage';
export * from './PerfilPage';